(function () {
  'use strict';

  window.__SIGLEP_ESTADOS__ = {

    federal: {
      uma_diaria:              117.31,
      uma_mensual:            3566.22,
      uma_anual:             42794.64,
      salario_minimo_general:  315.04,
      salario_minimo_frontera: 440.87,
    },

    estados: [
      {
        clave: 'AGS',
        nombre: 'Aguascalientes',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'BC',
        nombre: 'Baja California',
        salario_minimo_aplicable: 440.87,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.007,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'BCS',
        nombre: 'Baja California Sur',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'CAM',
        nombre: 'Campeche',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.06,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.20,
      },
      {
        clave: 'CHIS',
        nombre: 'Chiapas',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.20,
      },
      {
        clave: 'CHIH',
        nombre: 'Chihuahua',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'CHIH-ZFN',
        nombre: 'Chihuahua (Frontera Norte)',
        salario_minimo_aplicable: 440.87,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'CDMX',
        nombre: 'Ciudad de México',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.008,
        criterio_pension_local:   0.30,
      },
      {
        clave: 'COAH',
        nombre: 'Coahuila de Zaragoza',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'COAH-ZFN',
        nombre: 'Coahuila de Zaragoza (Frontera Norte)',
        salario_minimo_aplicable: 440.87,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'COL',
        nombre: 'Colima',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'DGO',
        nombre: 'Durango',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'GTO',
        nombre: 'Guanajuato',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'GRO',
        nombre: 'Guerrero',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.20,
      },
      {
        clave: 'HGO',
        nombre: 'Hidalgo',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'JAL',
        nombre: 'Jalisco',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.007,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'MEX',
        nombre: 'México',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'MICH',
        nombre: 'Michoacán de Ocampo',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'MOR',
        nombre: 'Morelos',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'NAY',
        nombre: 'Nayarit',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'NL',
        nombre: 'Nuevo León',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.007,
        criterio_pension_local:   0.30,
      },
      {
        clave: 'NL-ZFN',
        nombre: 'Nuevo León (Frontera Norte)',
        salario_minimo_aplicable: 440.87,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.007,
        criterio_pension_local:   0.30,
      },
      {
        clave: 'OAX',
        nombre: 'Oaxaca',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.20,
      },
      {
        clave: 'PUE',
        nombre: 'Puebla',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.06,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'QRO',
        nombre: 'Querétaro',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'QROO',
        nombre: 'Quintana Roo',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'SLP',
        nombre: 'San Luis Potosí',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'SIN',
        nombre: 'Sinaloa',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'SON',
        nombre: 'Sonora',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'SON-ZFN',
        nombre: 'Sonora (Frontera Norte)',
        salario_minimo_aplicable: 440.87,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'TAB',
        nombre: 'Tabasco',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'TAMS',
        nombre: 'Tamaulipas',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.007,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'TAMS-ZFN',
        nombre: 'Tamaulipas (Frontera Norte)',
        salario_minimo_aplicable: 440.87,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.007,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'TLAX',
        nombre: 'Tlaxcala',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.20,
      },
      {
        clave: 'VER',
        nombre: 'Veracruz de Ignacio de la Llave',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.06,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.25,
      },
      {
        clave: 'YUC',
        nombre: 'Yucatán',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.006,
        criterio_pension_local:   0.22,
      },
      {
        clave: 'ZAC',
        nombre: 'Zacatecas',
        salario_minimo_aplicable: 315.04,
        interes_legal_civil:      0.09,
        factor_arancelario:       0.005,
        criterio_pension_local:   0.22,
      },
    ],

  };
})();
